FROM node:18 as build-stage

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY .env ./
COPY ./smart_html_client ./smart_html_client

RUN npm run build

FROM nginx:alpine as production-stage
COPY --from=build-stage /usr/src/app/smart_html_client/dist /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
