version: '3.8'
services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile-client
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - smart-html-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
    networks:
      - smart-html-network

networks:
  smart-html-network:
