name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get Short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

     # Authenticate to Google Cloud
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_INFRA_KEY }}

    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker europe-docker.pkg.dev

    - name: Build and Push Docker Image for server
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-client
        push: true
        tags: europe-docker.pkg.dev/ethanwebcraft/imf/smart-html-server:${{ steps.slug.outputs.sha7 }}

    - name: Build and Push Docker Image for client
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-server
        push: true
        tags: europe-docker.pkg.dev/ethanwebcraft/imf/smart-html-client:${{ steps.slug.outputs.sha7 }}
